stages:
  data_ingestion: 
    cmd: python src/pipeline/stage_01_data_ingestion.py
    deps:
    - src/pipeline/stage_01_data_ingestion.py
    - src/component/data_ingestion.py
    - configs/config.yaml
    - raw_data/concrete_data.csv
    - src/entity/config_entity.py
    - src/config/configuration.py
    outs:
    - artifacts/DATA_INGESTION/train.csv
    - artifacts/DATA_INGESTION/test.csv
  
  data_transformation: 
    cmd: python src/pipeline/stage_02_data_transformation.py
    deps:
    - src/pipeline/stage_02_data_transformation.py
    - src/component/data_transformation.py
    - configs/config.yaml
    - artifacts/DATA_INGESTION/train.csv
    - artifacts/DATA_INGESTION/test.csv
    - src/entity/config_entity.py
    - src/config/configuration.py
    outs:
    - artifacts/DATA_TRANSFORMATION/processed_train.csv
    - artifacts/DATA_TRANSFORMATION/processed_test.csv
  
  model_training:
    cmd: python src/pipeline/stage_03_model_training.py
    deps:
    - src/pipeline/stage_03_model_training.py
    - src/component/model_training.py
    - configs/config.yaml
    - configs/params.yaml
    - artifacts/DATA_TRANSFORMATION/processed_train.csv
    - src/entity/config_entity.py
    - src/config/configuration.py 
    

  model_evaluation:
    cmd: python src/pipeline/stage_04_model_evaluation.py
    deps: 
    - src/pipeline/stage_04_model_evaluation.py
    - src/component/model_evaluation.py
    - configs/config.yaml
    - artifacts/DATA_TRANSFORMATION/processed_test.csv
    - src/entity/config_entity.py
    - src/config/configuration.py
    outs: 
    - artifacts/MODEL_EVALUATOR/test_results.json