target : "concrete_compressive_strength"
raw_data : raw_data/concrete_data.csv
model_dir: models
scaler_file: scaler.pkl
model_file: model.pkl
artifacts: 
  dir: artifacts
  ingestion: DATA_INGESTION
  transformation: DATA_TRANSFORMATION
  trainer: MODEL_TRAINER
  evaluator: MODEL_EVALUATOR
  train_data: train.csv
  test_data: test.csv
  transformation_train: processed_train.csv
  transformation_test: processed_test.csv
  results: experiment_results.csv
  result_file: test_results.json