name: DVC Stage.
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Pipeline
        env: 
          repo_token: ${{ secrets.TOKEN_GITHUB }}
        run: |
          pip install -r requirements.txt
          pip install -e .
          dvc repro -v